nutriapp/anthrocalc/urls.py
from django.conf.urls import url

from .patient_graph import simple, graph_for_person



app_name="nutriapp"

#
urlpatterns = [
    url(r'charts/simple.png$', simple),
    url(r'charts/personal_progress.png$', graph_for_person),
]

nutriapp/nutriapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

app_name="nutriapp"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('anthrocalc.patient_views_urls', namespace='patients')),
    url(r'^', include('anthrocalc.visit_views_urls', namespace='visits')),
    url(r'^', include('anthrocalc.metrics_views_urls', namespace='metrics')),
    url(r'^', include('anthrocalc.urls', namespace='antrobase')),
    # FIXME namespace should be anthro???

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nutriapp/anthrocalc/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now

# Create your models here.


class Family(models.Model):
    responsible_name = models.TextField(null=False)

    def __str__(self):
        return self.responsible_name


class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    # Full Name
    code = models.CharField(max_length=50, verbose_name="Código")
    name = models.CharField(max_length=250, verbose_name="Nombre")

    # M or F
    gender = models.CharField(max_length=1, verbose_name="Sexo")

    # Day of Birth
    dob = models.DateField(verbose_name="Fecha de Nacimiento")

    family = models.ForeignKey(Family, on_delete=models.SET_NULL, null=True, verbose_name="Familia")

    def __str__(self):
        return " de ".join([self.name, self.family.responsible_name])

    #TODO: moar info


class MultipleVisit(models.Model):
    date = models.DateTimeField(default=now)


# A point in time where metrics are taken
class Visit(models.Model):
    # def __init__(self, *args, **kwargs):
    #     super(Visit, self).__init__(*args, **kwargs)
    #
    # def __init__(self, multiple_visit, *args, **kwargs):
    #     super(Visit, self).__init__(*args, **kwargs)
    #     self.date = multiple_visit.date

    # TODO: check UTC policy
    # https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.DateField.auto_now_add
    date = models.DateTimeField(default=now)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    notes = models.TextField(verbose_name="Notas", null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.patient.name, self.date)


class Metric(models.Model):
    weight = models.FloatField(verbose_name="Peso (kg)")
    height = models.FloatField(verbose_name="Altura (cm)")
    standing_or_upright = models.NullBooleanField( verbose_name="¿Fue medido de pie / parado?")
    # TODO: add moar metrics


    def __str__(self):
        return "weight: {} - height: {}".format(self.weight, self.height)


    visit = models.OneToOneField(Visit, on_delete=models.CASCADE, verbose_name="Visita")  # TODO: check this relationship


## A visit includes a set of metrics, given the living conditions
class EnvironmentMetric(models.Model):


    visit = models.ForeignKey(Visit, on_delete=models.CASCADE)


# Treatments or actions taken to fix the condition
class Action(models.Model):
    action_type = models.TextField()
    value = models.TextField()

    visit = models.ForeignKey(Visit, on_delete=models.CASCADE)  # TODO: check this relationship

nutriapp/anthrocalc/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
from .models import *

from .person_utils import fetch_historical_metrics



# Views for Patients

class PatientList(ListView):
    model = Patient


class PatientDetail(DetailView):
    model = Patient

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        visits = Visit.objects.filter(patient=self.object.id)
        context['visits'] = visits
        context['metrics_dict'] = fetch_historical_metrics(self.object.id)
        return context


class PatientCreation(CreateView):
    model = Patient
    success_url = reverse_lazy('patients:list')
    fields = ['name', 'dob', 'family']


class PatientUpdate(UpdateView):
    model = Patient
    success_url = reverse_lazy('patients:list')
    fields = ['name', 'dob', 'family']


class PatientDelete(DeleteView):
    model = Patient
    success_url = reverse_lazy('patients:list')


# Views for Visits


class VisitList(ListView):
    model = Visit

    ordering = ['-date']

class VisitDetail(DetailView):
    model = Visit

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['metrics'] = Metric.objects.filter(visit=self.object.id)
        return context


class VisitCreation(CreateView):
    model = Visit
    metric = Metric
    success_url = reverse_lazy('visits:list') ## TODO: redirect to new metric
    #success_url = reverse_lazy('metrics:newvm')
    #+"?visit={{visit.id}}"
    # ", args=metric.id)
    fields = '__all__'

    def get_success_url(self):
        return reverse('visits:detail',args=(self.object.id,))

    def get_initial(self):
        initial = super().get_initial()
        if "patient" in self.request.GET:
            initial['patient'] = self.request.GET["patient"]
        return initial


class VisitUpdate(UpdateView):
    model = Visit
    success_url = reverse_lazy('visits:list')
    fields = ['patient', 'date']


class VisitDelete(DeleteView):
    model = Visit
    success_url = reverse_lazy('visits:list')


# Views for Metrics


class MetricList(ListView):
    model = Metric


class MetricDetail(DetailView):
    model = Metric


class MetricCreation(CreateView):
    model = Metric
    # success_url = reverse_lazy('visits:list')
    fields = "__all__"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     if "visit" in self.request.GET:
    #         visit_id = self.request.GET["visit"]
    #         context['visit'] = Visit.objects.filter(id=visit_id)
    #     return context

    def get_initial(self):
        initial = super().get_initial()
        if "visit" in self.request.GET:
            visit_id = self.request.GET["visit"]
            initial["visit"] = visit_id
        return initial

    def get_success_url(self):
        return reverse('visits:detail',args=(self.object.visit.id,))
    # fields = ['visit.patient', 'weight', 'height']


class MetricUpdate(UpdateView):
    model = Metric
    fields = ['weight', 'height', 'standing_or_upright']

    def get_success_url(self):
        return reverse('visits:detail',args=(self.object.visit.id,))


class MetricDelete(DeleteView):
    model = Metric
    success_url = reverse_lazy('metrics:list')

nutriapp/anthrocalc/templates/anthrocalc/base.html
{% load staticfiles %}
<!doctype html>
<html lang="es">
    <head>
        <title>{% block title %} NutriAcción {% endblock %}</title>
        <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="container">
          <h1>Nutri Acción</h1>
          <nav class="nav justify-content-end">
            <a class="nav-link" href='{% url "patients:list" %}'>Listado de Niños</a>
            <a class="nav-link" href='{% url "visits:list" %}'>Listado de Visitas</a>
            <a class="nav-link" href='{% url "metrics:list" %}'>Listado de Métricas</a>
            <a class="nav-link disabled" href="#">Mas opciones...</a>
          </nav>
        </div>
        <div class="content container">
          {% block content %}
          {% endblock %}
        </div>
    </body>
</html>

nutriapp/anthrocalc/templates/anthrocalc/metric_confirm_delete.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar esta metrica "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/metric_detail.html
{% extends 'anthrocalc/base.html' %}

{% block content %}

<h1>Medición del niño: {{ metric.visit.patient.name }}</h1>
<p>Fecha de visita: <i>{{ metric.visit.date }}</i></p>

<strong>Peso:</strong> {{metric.weight}} <br />
<strong>Altura:</strong> {{metric.height}}

<p>
  <a href='{% url "metrics:edit" metric.id %}'>Editar esta medición.</a><br/>


    <a href='{% url "visits:detail" metric.visit.id %}'>Volver a Visita.</a>
    <a href='{% url "patients:detail" metric.visit.patient.id %}'>Información del Niño.</a>
    <br />
    <a href='{% url "visits:list" %}'>Listado de Mediciones.</a>

</p>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/metric_form.html
{% extends 'anthrocalc/base.html' %}


{% block content %}
<style>
#id_visit {
  color:#CCC;
}
</style>
<h1>Creando medición para: {{ visit.patient.name }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/metric_list.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<h1>Listado de Metricas</h1>
<p>
    <a class="btn btn-primary" role="button" href='{% url "metrics:new" %}'>Crear nueva medición</a>
</p>
<ul>
    {% for metrica in object_list %}
        <li>
            <p> Medición de: {{ metrica.visit.patient.name }} - {{ metrica.visit.date }}
            </p>
            <p>
                <a href='{% url "metrics:detail" metrica.id %}'>Ver</a> |
                <a href='{% url "metrics:edit" metrica.id %}'>Editar</a> |
                <a href='{% url "metrics:delete" metrica.id %}'>Borrar</a>
            </p>
        </li>
    {% endfor %}
</ul>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/patient_confirm_delete.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el paciente "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/patient_detail.html
{% extends 'anthrocalc/base.html' %}
{% load staticfiles %}

{% block content %}
<h1>Información de: {{ patient.name }}</h1>
<p>Fecha de nacimiento: <i>{{ patient.dob }}</i></p>
<!-- TODO: agregar info de madre -->

<h2>Visitas y Medidas</h2>
<ol>
{% for id, metrical in metrics_dict.items %}
  <li><a href={% url 'visits:detail' id %}>{{ metrical.date }}</a>
    {% if metrical.metrics %} <br/>
    Peso: {{metrical.metrics.weight}} - Talla: {{metrical.metrics.height}}
    {% endif %}
  </li>
  {{metric}}
{% endfor %}
</ol>

<a class="btn btn-warning" role="button" href='{% url "patients:edit" patient.id %}'>Editar información.</a>
<a class="btn btn-danger" role="button" href='{% url "patients:delete" patient.id %}'>Borrar niño</a>
<hr />
<p>
    <a class="btn btn-primary" role="button" href='{% url "visits:new" %}?patient={{ patient.id }}'><img src="{% static '/icons/svg/plus.svg' %}">Agregar visita al paciente</a>

    <a class="btn btn-secondary" role="button" href='{% url "patients:list" %}'>Regresar</a>
</p>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/patient_form.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/patient_list.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<h1>Niños registrados:</h1>
<p>
    <a class="btn btn-primary" role="button" href='{% url "patients:new" %}'>Agregar nuevo niño</a>
</p>
<table>
    {% for patient in object_list %}
        <tr>
            <td><a href='{% url "patients:detail" patient.id %}'>{{ patient.name }}</a></td>
            <td>
                Nacido el: {{patient.dob}}</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/visit_confirm_delete.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar esta visita "{{ object }}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/visit_detail.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<h1>Visita del niño: <a href='{% url "patients:detail" visit.patient.id %}'><strong>{{ visit.patient.name }}</strong></a></h1>
<h2>Información del niño</h2>
<strong>Código: </strong> {% firstof visit.patient.code visit.patient.id %}<br/>
<strong>Nombre del familiar: </strong> {{visit.patient.family.responsible_name}} <br/>
<strong>Nacido en: </strong><i>{{ visit.patient.dob }}</i>

<hr />

<h2>Información de visita</h2>
<p>Fecha de visita: <i>{{ visit.date }}</i></p>
<p>
En esta visita se realizó:<br/>
{% for metric in metrics %}
  <h3><a href='{% url "metrics:detail" metric.id %}'>Medición:</a></h3>
  <strong>Peso:</strong> {{metric.weight}} kg.<br />
  <strong>Talla:</strong> {{metric.height}} cm.<br />
  <a class="btn btn-primary" role="button" href='{% url "metrics:edit" metric.id %}'>Editar esta medición.</a>
{% endfor %}

Observaciones: {{visit.notes|default:"n/a"}}
</p>
<hr />
<p>
    {% if not metrics %}
      <a class="btn btn-success" role="button" href='{% url "metrics:new" %}?visit={{visit.id}}'>Medir</a>
    {% endif %}
    <a class="btn btn-secondary" role="button" ref='{% url "visits:list" %}'>Regresar</a>
</p>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/visit_form.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% if visit.id %}
    <a href='{% url "metrics:new" %}?visit={{visit.id}}'>Agregar medición</a>
    {% endif %}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

nutriapp/anthrocalc/templates/anthrocalc/visit_list.html
{% extends 'anthrocalc/base.html' %}

{% block content %}
<h1>Listado de Visitas</h1>
<p>
    <a class="btn btn-primary" role="button" href='{% url "visits:new" %}'>Crear Visita</a>
</p>
<ul>
    {% for visit in object_list %}
        <li>
            <p>{{ visit.patient.name }} - {{ visit.date }} </p>
            <p>
                <a href='{% url "visits:detail" visit.id %}'>Ver</a> |
                <a href='{% url "visits:edit" visit.id %}'>Editar</a> |
                <a href='{% url "visits:delete" visit.id %}'>Borrar</a>
            </p>
        </li>
    {% endfor %}
</ul>
{% endblock %}